index:
    path: /
    controller: App\Controller\UserController::index

register_user:
    path: /user/registration
    controller: App\Controller\UserController::registerUser

login_user:
    path: /user/login
    controller: App\Controller\UserController::loginUser

authenticate_user:
    path: /user/authenticate
    controller: App\Controller\UserController::authenticateUser

show_storefront:
    path: /catalog
    controller: App\Controller\StorefrontController::showStorefront

create_product:
    path: /product/create
    controller: App\Controller\StorefrontController::createProduct