index:
    path: /
    controller: App\Controller\UserController::index

register_user:
    path: /user/registration
    controller: App\Controller\UserController::registerUser

show_storefront:
    path: /catalog
    controller: App\Controller\StorefrontController::showStorefront
